### ISSUE TITLE
How do I create a partition table?

### ISSUE THREAD

**Issue by otaxhu** [igrr/nvs-dotenv#1]
I know this is off-topic of your library, I found this library very useful so I hope that you can help me.

So in your [README.md](https://github.com/igrr/nvs-dotenv/blob/main/README.md) you say that you have to edit "your" partition table and add that new value, but when I generate a new project, it doesn't create any .csv file, and when I try to compile anyways, prints a message saying "No 'dotenv' partition found, not storing environment in NVS."

**Comment by otaxhu** [comment]
For more context, I cloned the repo, not through `idf.py add-dependency`

**Comment by igrr** [comment]
You can find information about creating partition tables here: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-guides/partition-tables.html. You can also check some of the ESP-IDF examples over here, they are all defining custom partition tables: https://github.com/espressif/esp-idf/tree/master/examples/storage/partition_api

**Comment by otaxhu** [comment]
Thank you for your help, I found another problem with the building of `dotenv.bin` file, guess gonna open another issue to explain it.
